<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?>
<style>.ard-card{background:#fff;border:1px solid #edf2f7;border-radius:28px;box-shadow:0 18px 46px rgba(15,23,42,.07);padding:28px}.ard-title{font-weight:950;color:#0f172a}.ard-sub{color:#64748b}.ard-badge{display:inline-flex;align-items:center;gap:6px;padding:9px 12px;border-radius:999px;font-size:12px;font-weight:950}.ard-badge.success{background:#dcfce7;color:#15803d}.ard-badge.warning{background:#fef3c7;color:#92400e}.ard-badge.danger{background:#fee2e2;color:#b91c1c}.ard-table{width:100%;border-collapse:separate;border-spacing:0 12px}.ard-table td,.ard-table th{padding:14px;border-top:1px solid #edf2f7;border-bottom:1px solid #edf2f7;background:#fff}.ard-table th{font-size:12px;color:#64748b;text-transform:uppercase}.ard-table td:first-child,.ard-table th:first-child{border-left:1px solid #edf2f7;border-radius:16px 0 0 16px}.ard-table td:last-child,.ard-table th:last-child{border-right:1px solid #edf2f7;border-radius:0 16px 16px 0}.doc{width:42px;height:42px;border-radius:14px;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;background:#e0f2fe;color:#0369a1}.btn{border-radius:16px;font-weight:900}</style>
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<?php $currency=fn($v)=>'Rp '.number_format((float)$v,0,',','.'); $s=strtolower((string)($report['status_verifikasi'] ?? 'pending')); $m=$s==='approved'?['class'=>'success','text'=>'Disetujui','icon'=>'fa-circle-check']:($s==='rejected'?['class'=>'danger','text'=>'Perlu Perbaikan','icon'=>'fa-circle-xmark']:['class'=>'warning','text'=>'Menunggu','icon'=>'fa-clock']); ?>
<div class="ard-card mb-4"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap"><div><span class="ard-badge <?= $m['class'] ?>"><i class="fa-solid <?= $m['icon'] ?>"></i> <?= esc($m['text']) ?></span><h2 class="ard-title mt-3 mb-2"><?= esc($report['judul_laporan'] ?? '-') ?></h2><p class="ard-sub mb-0"><?= esc($report['nama_yayasan'] ?? '-') ?> • <?= esc($report['campaign_judul'] ?? '-') ?></p></div><a href="<?= base_url('admin/report') ?>" class="btn btn-light px-4 py-3"><i class="fa-solid fa-arrow-left me-2"></i> Kembali</a></div></div>
<div class="row g-4"><div class="col-xl-8"><div class="ard-card"><h4 class="ard-title fs-4 mb-3">Deskripsi</h4><p class="ard-sub"><?= nl2br(esc($report['deskripsi'] ?? '-')) ?></p><h4 class="ard-title fs-4 mt-4 mb-3">Rincian</h4><table class="ard-table"><thead><tr><th>Pengeluaran</th><th>Nominal</th><th>Keterangan</th><th>Dokumen</th></tr></thead><tbody><?php foreach($details as $detail): ?><tr><td><strong><?= esc($detail['nama_pengeluaran'] ?? '-') ?></strong></td><td><strong><?= $currency($detail['nominal'] ?? 0) ?></strong></td><td><?= esc($detail['keterangan'] ?? '-') ?></td><td><?php if(!empty($detail['foto'])): ?><a class="doc" href="<?= base_url('uploads/laporan/'.$detail['foto']) ?>" target="_blank"><i class="fa-solid fa-file-arrow-down"></i></a><?php else: ?>-<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-4"><div class="ard-card"><h4 class="ard-title fs-4 mb-3">Verifikasi Admin</h4><p class="ard-sub">Total pengeluaran</p><h3 class="ard-title"><?= $currency($report['total_pengeluaran'] ?? 0) ?></h3><?php if($s==='pending'): ?><div class="d-grid gap-2 mt-4"><form action="<?= base_url('admin/report/approve/'.$report['id']) ?>" method="post"><?= csrf_field() ?><button class="btn btn-success py-3" type="submit"><i class="fa-solid fa-check me-2"></i> Setujui Laporan</button></form><form action="<?= base_url('admin/report/reject/'.$report['id']) ?>" method="post"><?= csrf_field() ?><button class="btn btn-warning py-3" type="submit"><i class="fa-solid fa-xmark me-2"></i> Minta Perbaikan</button></form></div><?php else: ?><div class="alert alert-light rounded-4 fw-bold mt-4">Laporan sudah diproses.</div><?php endif; ?></div></div></div>
<?= $this->endSection() ?>
