<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?>
<style>.ar-card{background:#fff;border:1px solid #edf2f7;border-radius:28px;box-shadow:0 18px 46px rgba(15,23,42,.07);padding:28px}.ar-title{font-weight:950;color:#0f172a}.ar-subtitle{color:#64748b}.ar-filter{display:grid;grid-template-columns:1fr 220px 180px;gap:14px}.ar-filter .form-control,.ar-filter .form-select{border-radius:18px;min-height:52px}.ar-table{width:100%;border-collapse:separate;border-spacing:0 12px;table-layout:fixed}.ar-table th{font-size:12px;color:#64748b;text-transform:uppercase;letter-spacing:.06em;padding:0 14px 8px}.ar-table td{background:#fff;border-top:1px solid #edf2f7;border-bottom:1px solid #edf2f7;padding:16px 14px;vertical-align:middle}.ar-table td:first-child{border-left:1px solid #edf2f7;border-radius:18px 0 0 18px}.ar-table td:last-child{border-right:1px solid #edf2f7;border-radius:0 18px 18px 0}.ar-main strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ar-main small{display:block;color:#64748b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ar-badge{display:inline-flex;align-items:center;gap:6px;padding:8px 11px;border-radius:999px;font-size:12px;font-weight:950}.ar-badge.success{background:#dcfce7;color:#15803d}.ar-badge.warning{background:#fef3c7;color:#92400e}.ar-badge.danger{background:#fee2e2;color:#b91c1c}.ar-btn{width:42px;height:42px;border-radius:14px;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;background:#e0f2fe;color:#0369a1}@media(max-width:992px){.ar-filter{grid-template-columns:1fr}.ar-table thead{display:none}.ar-table,.ar-table tbody,.ar-table tr,.ar-table td{display:block;width:100%}.ar-table tr{border:1px solid #edf2f7;border-radius:22px;padding:14px;margin-bottom:14px}.ar-table td{border:0!important;border-radius:0!important;padding:8px 0}.ar-table td:before{content:attr(data-label);display:block;font-size:11px;font-weight:900;color:#64748b;text-transform:uppercase;margin-bottom:4px}}</style>
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<?php $currency=fn($v)=>'Rp '.number_format((float)$v,0,',','.'); $statusMeta=function($s){$s=strtolower((string)$s); if($s==='approved')return['class'=>'success','text'=>'Disetujui','icon'=>'fa-circle-check']; if($s==='rejected')return['class'=>'danger','text'=>'Perlu Perbaikan','icon'=>'fa-circle-xmark']; return['class'=>'warning','text'=>'Menunggu','icon'=>'fa-clock'];}; ?>
<div class="ar-card mb-4"><h2 class="ar-title mb-1">Verifikasi Laporan Dana</h2><p class="ar-subtitle mb-0">Periksa laporan penggunaan dana dari yayasan sebelum dipublikasikan.</p></div>
<div class="ar-card mb-4"><form method="get" action="<?= base_url('admin/report') ?>" class="ar-filter"><input type="text" name="keyword" value="<?= esc($keyword ?? '') ?>" class="form-control" placeholder="Cari laporan, campaign, atau yayasan..."><select name="status" class="form-select"><option value="">Semua Status</option><option value="pending" <?= ($status ?? '')==='pending'?'selected':'' ?>>Menunggu</option><option value="approved" <?= ($status ?? '')==='approved'?'selected':'' ?>>Disetujui</option><option value="rejected" <?= ($status ?? '')==='rejected'?'selected':'' ?>>Perlu Perbaikan</option></select><button class="btn btn-primary rounded-4 fw-bold"><i class="fa-solid fa-magnifying-glass me-2"></i> Filter</button></form></div>
<div class="ar-card"><h4 class="ar-title fs-3 mb-3">Daftar Laporan</h4><?php if(empty($reports)): ?><div class="alert alert-light rounded-4 fw-bold">Belum ada laporan.</div><?php else: ?><table class="ar-table"><thead><tr><th>Laporan</th><th>Yayasan</th><th>Campaign</th><th>Pengeluaran</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($reports as $report): ?><?php $m=$statusMeta($report['status_verifikasi'] ?? 'pending'); ?><tr><td data-label="Laporan"><div class="ar-main"><strong><?= esc($report['judul_laporan'] ?? '-') ?></strong><small><?= date('d M Y',strtotime($report['tanggal_laporan'] ?? $report['created_at'] ?? date('Y-m-d'))) ?></small></div></td><td data-label="Yayasan"><?= esc($report['nama_yayasan'] ?? '-') ?></td><td data-label="Campaign"><?= esc($report['campaign_judul'] ?? '-') ?></td><td data-label="Pengeluaran"><strong><?= $currency($report['total_pengeluaran'] ?? 0) ?></strong></td><td data-label="Status"><span class="ar-badge <?= $m['class'] ?>"><i class="fa-solid <?= $m['icon'] ?>"></i> <?= esc($m['text']) ?></span></td><td data-label="Aksi"><a class="ar-btn" href="<?= base_url('admin/report/detail/'.$report['id']) ?>" title="Detail"><i class="fa-solid fa-eye"></i></a></td></tr><?php endforeach; ?></tbody></table><?php if(!empty($pager)): ?><div class="mt-3"><?= $pager->links('admin_reports','default_full') ?></div><?php endif; ?><?php endif; ?></div>
<?= $this->endSection() ?>
